/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hardware;
import Software.Program;

public class Computer {

    public Memory memory;
    public Program program;

    public Computer(Memory memory){
        this.memory = memory;
    }

    public void load(Program program){
        this.program = program;
    }
    public void run() {
        ProgramCounter programCounter = new ProgramCounter();
         
        while (programCounter.get() != -1) {
            try {
                program.getInstruction(programCounter.get()).execute(memory, programCounter);
            } catch (ClassCastException e) {
                throw new ClassCastException("Computer cannot run!");
            }
        }
    }
}